### ISSUE TITLE
Issue with manual alignment

### ISSUE THREAD

**Issue by ajnam03** [mcellteam/swift-ir#5]
1) In manual mode, the reference/transforming sections are correctly displayed in far left panel. However, the images displayed in the middle toggle panel are incorrect (i.e. correspond to the wrong sections). This is not the case when you exit manual mode - correct image is displayed. Also, refreshing, closing/reopening, starting a new project with the same images doesn't seem to solve the problem. 
2) (In manual mode) Middle panel, the instructions for placing match regions is missing the word "shift" before "+ click"

**Comment by joelyancey** [comment]
Hi @ajnam03  thanks -- fixed it in the new release. Will try to make it usable on TACC this week...
